// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiFamilyPortal.SaaS.Data;

#nullable disable

namespace MultiFamilyPortal.SaaS.Migrations
{
    [DbContext(typeof(TenantContext))]
    partial class TenantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiFamilyPortal.SaaS.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DatabaseSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleSiteVerification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsREMentorStudent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7285abc4-fd5b-4436-a9de-4a951410eefa"),
                            Created = new DateTimeOffset(new DateTime(2024, 4, 15, 23, 12, 19, 211, DateTimeKind.Unspecified).AddTicks(5379), new TimeSpan(0, 0, 0, 0, 0)),
                            DatabaseSchema = "local",
                            Disabled = false,
                            Environment = "Development",
                            Host = "localhost",
                            IsREMentorStudent = false
                        },
                        new
                        {
                            Id = new Guid("c04cd58c-39bf-4567-abff-8cdf6a46e87b"),
                            Created = new DateTimeOffset(new DateTime(2024, 4, 15, 23, 12, 19, 211, DateTimeKind.Unspecified).AddTicks(5395), new TimeSpan(0, 0, 0, 0, 0)),
                            DatabaseSchema = "quarter",
                            Disabled = false,
                            Environment = "Development",
                            Host = "quarterdemo",
                            IsREMentorStudent = false
                        },
                        new
                        {
                            Id = new Guid("983d007d-1f68-468a-80d9-3cf58e1c46cf"),
                            Created = new DateTimeOffset(new DateTime(2024, 4, 15, 23, 12, 19, 211, DateTimeKind.Unspecified).AddTicks(5396), new TimeSpan(0, 0, 0, 0, 0)),
                            DatabaseSchema = "homyre",
                            Disabled = false,
                            Environment = "Development",
                            Host = "homyredemo",
                            IsREMentorStudent = false
                        },
                        new
                        {
                            Id = new Guid("6c060c90-0c7e-4e36-b419-0224ba6f21da"),
                            Created = new DateTimeOffset(new DateTime(2024, 4, 15, 23, 12, 19, 211, DateTimeKind.Unspecified).AddTicks(5397), new TimeSpan(0, 0, 0, 0, 0)),
                            DatabaseSchema = "underwriter",
                            Disabled = false,
                            Environment = "Development",
                            Host = "underwriter",
                            IsREMentorStudent = false
                        },
                        new
                        {
                            Id = new Guid("5946dcc3-c62e-44c0-b994-8cf2591910f5"),
                            Created = new DateTimeOffset(new DateTime(2024, 4, 15, 23, 12, 19, 211, DateTimeKind.Unspecified).AddTicks(5398), new TimeSpan(0, 0, 0, 0, 0)),
                            DatabaseSchema = "mfpdisabled",
                            Disabled = false,
                            Environment = "Development",
                            Host = "mfpdisabled",
                            IsREMentorStudent = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
